version: "3"

# here we list our containers
services:

  express-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    depends_on:
      - mongodb
      - redisdb

  mongodb:
    image: mongo

  redisdb:
    image: redis

volumes:
  mongo-db:
